version: 2.1
executors:
  node:
    docker:
      - image: circleci/node:10.16.3
jobs:
  build:
    executor: node
    steps:
      - checkout
      - restore_cache:
          name: Restore Yarn Package Cache
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
      - run:
          name: Install Dependencies
          command: yarn --frozen-lockfile
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
      - run: yarn build
  test:
    executor: node
    steps:
      - checkout
      - run: yarn test --passWithNoTests

  deploy:
    executor: node
    steps:
      - add_ssh_keys:
      - run: |
          echo '$SSH_HOST ecdsa-sha2-nistp256 SHA256:s1oJsUUbUvR+d0NIhFVXOwHwa3buiqTiptQq6XeE6E4' >> ~/.ssh/known_hosts
      - run:
          name: Deploy over SSH
          command: |
            ssh $SSH_USER@$SSH_HOST -v "cd ~/repo/scpbot && git pull && yarn build"

workflows:
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - hold:
          type: approval
          requires:
            - test
      - deploy:
          requires:
            - hold
